import ThemeRegistry from "@/lib/themeregistry";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<AppRouterCacheProvider>
					<ThemeRegistry>{children}</ThemeRegistry>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
