// Klistrar in detta i chrome konsollen bara för att ha något att arbeta med.
// MOCK EVENTS
const mockEvents = [
	{
		id: 1,
		title: "Morning Yoga Session",
		activityCategory: "sport",
		date: "2025-11-06",
		startTime: "07:00",
		createdBy: 2,
		eventType: "activity",
		membersId: [1, 2, 5, 7],
		notes: "Bring your own mat. Beginner friendly!",
	},
	{
		id: 2,
		title: "Team Lunch",
		activityCategory: "social",
		date: "2025-11-07",
		startTime: "12:30",
		createdBy: 1,
		eventType: "meal",
		membersId: [1, 2, 3, 4, 6],
		notes: "New Italian restaurant downtown",
	},
	{
		id: 3,
		title: "JavaScript Workshop",
		activityCategory: "education",
		date: "2025-11-08",
		startTime: "14:00",
		createdBy: 3,
		eventType: "activity",
		membersId: [2, 3, 8],
		notes: "Advanced async patterns and error handling",
	},
	{
		id: 4,
		title: "Breakfast Club",
		activityCategory: "social",
		date: "2025-11-08",
		startTime: "08:30",
		createdBy: 4,
		eventType: "meal",
		membersId: [1, 4, 5, 6],
		notes: "Trying the new café on Main Street",
	},
	{
		id: 5,
		title: "Basketball Game",
		activityCategory: "sport",
		date: "2025-11-09",
		startTime: "18:00",
		createdBy: 4,
		eventType: "activity",
		membersId: [1, 4, 5, 6, 7, 8],
		notes: "Outdoor court, weather permitting",
	},
	{
		id: 6,
		title: "Dinner Party",
		activityCategory: "social",
		date: "2025-11-10",
		startTime: "19:00",
		createdBy: 5,
		eventType: "meal",
		membersId: [2, 5, 6, 7],
		notes: "Potluck style - bring a dish to share",
	},
	{
		id: 7,
		title: "Morning Run",
		activityCategory: "sport",
		date: "2025-11-11",
		startTime: "06:30",
		createdBy: 1,
		eventType: "activity",
		membersId: [1, 3, 7],
		notes: "5K route along the waterfront",
	},
	{
		id: 8,
		title: "Sunday Brunch",
		activityCategory: "social",
		date: "2025-11-12",
		startTime: "11:00",
		createdBy: 6,
		eventType: "meal",
		membersId: [2, 4, 6, 8],
		notes: "Bottomless mimosas available!",
	},
	{
		id: 9,
		title: "Cooking Class",
		activityCategory: "hobby",
		date: "2025-11-13",
		startTime: "17:00",
		createdBy: 7,
		eventType: "activity",
		membersId: [1, 2, 3, 5],
		notes: "Learn to make homemade pasta",
	},
	{
		id: 10,
		title: "Pizza Night",
		activityCategory: "social",
		date: "2025-11-14",
		startTime: "18:30",
		createdBy: 8,
		eventType: "meal",
		membersId: [1, 2, 3, 4, 5, 6, 7, 8],
		notes: "Movie marathon at Jake's place",
	},
];

localStorage.setItem("events", JSON.stringify(mockEvents));
